### ISSUE TITLE
error in running ./make.py

### ISSUE THREAD

**Issue by tejalbarnwal** [openmv/tensorflow-lib#12]
Hey,
If I run `make.py`, I get the following error:
![image](https://github.com/openmv/tensorflow-lib/assets/64950661/b23f9eaf-3a1c-4f25-92d1-b725fe9cdfcc)

If I comment out the following line
`#include "edge-impulse-sdk/dsp/kissfft/kiss_fftr.h"` in `rfft2d.cc`,
I get more error.

Please help me

**Comment by iabdalkader** [comment]
@kwagyeman

**Comment by kwagyeman** [comment]
Will set this up with GitHub actions.

**Comment by kwagyeman** [comment]
Fixed via included edge impulse sdk.
