### ISSUE TITLE
Pass debug function pointer from py_tf.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/tensorflow-lib#16]
https://github.com/openmv/tensorflow-lib/blob/8233af9b856f4d14c60efe520d35ce75214b3d7d/libtf.cc#L23

**Comment by kwagyeman** [comment]
Please clarify: Do I need to expose the three variables?

**Comment by iabdalkader** [comment]
You can remove all of that and just pass a function pointer in `params`, from `py_tf`, that just prints the output if debugging is enabled. Debugging output can be controlled with a variable passed to `load` functions, or a model attribute. There's no need to allocate buffers. Alternatively, if you want to buffer the output for exception messages, you can leave everything as is, and basically just move `libtf_debug_log` to `py_tf`.

**Comment by iabdalkader** [comment]
https://github.com/openmv/tensorflow-lib/pull/17
