### ISSUE TITLE
With a fresh clone make.py must be run a few times before it builds successfully

### ISSUE THREAD

**Issue by iabdalkader** [openmv/tensorflow-lib#4]
Build errors like this:

`_data_int8_grayscale_2020_05_27.zip" "a0ede2d058aa2a1d413893455dd55352" tensorflow/lite/micro/tools/make/downloads/person_model_int8  
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/micro/tools/make/downloads/person_model_grayscale/no_person_image_data.o', needed by 'tensorflow/lite/micro/tools/make/gen/linux_x86_64/bin/person_detection_test'.  Stop.
make: *** Waiting for unfinished jobs....
downloading https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip
downloading https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_micro_person_data_grayscale_2020_05_27.zip
downloading https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz
downloading https://github.com/google/ruy/archive/34ea9f4993955fa1ff4eb58e504421806b7f2e8f.zip
downloading https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_micro_person_data_int8_grayscale_2020_05_27.zip
downloading https://storage.googleapis.com/download.tensorflow.org/models/tflite/cifar_image_recognition_model_2020_05_27.zip
downloading https://github.com/mborgerding/kissfft/archive/v130.zip
downloading https://github.com/google/flatbuffers/archive/v1.12.0.tar.gz
Finished patching kissfft
Make Failed...
`

**Comment by kwagyeman** [comment]
It's because of the -j4 in the make. I should probably make that only happen after you have the downloads. The Google Make file can't handle multiple threads when downloading.

**Comment by iabdalkader** [comment]
Yes please do it because it also gets stuck sometimes and you have to run it a few times ignoring the build errors.

**Comment by iabdalkader** [comment]
@kwagyeman Was this fixed ?

**Comment by kwagyeman** [comment]
I'm working on the library.
